<div class="jumbotron">
    <h1><?= $this->translate('welcome') ?></h1>

    <p><?= $this->translate('description') ?>
    <ul>
        <li><a href="<?= $this->url('home', [], ['query' => ['lang' => 'en']]) ?>">English</a></li>
        <li><a href="<?= $this->url('home', [], ['query' => ['lang' => 'de']]) ?>">German</a></li>
        <li><a href="<?= $this->url('home', [], ['query' => ['lang' => 'ru']]) ?>">Russian</a></li>
    </ul>
</div>

